//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.18

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

import 'package:pesu_api/api.dart';
import 'package:test/test.dart';

// tests for AdminSendCoinsRequest
void main() {
  // final instance = AdminSendCoinsRequest();

  group('test AdminSendCoinsRequest', () {
    // int coins
    test('to test the property `coins`', () async {
      // TODO
    });

    // String reason
    test('to test the property `reason`', () async {
      // TODO
    });

    // Generated by the panel per attempt; a retried click can't credit twice
    // String requestId
    test('to test the property `requestId`', () async {
      // TODO
    });


  });

}
