//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.18

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

library pesu_api;

import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:collection/collection.dart';
import 'package:http/http.dart';
import 'package:intl/intl.dart';
import 'package:meta/meta.dart';

part 'api_client.dart';
part 'api_helper.dart';
part 'api_exception.dart';
part 'auth/authentication.dart';
part 'auth/api_key_auth.dart';
part 'auth/oauth.dart';
part 'auth/http_basic_auth.dart';
part 'auth/http_bearer_auth.dart';

part 'api/admin_api.dart';
part 'api/auth_api.dart';
part 'api/calls_api.dart';
part 'api/chat_api.dart';
part 'api/companion_api.dart';
part 'api/companions_api.dart';
part 'api/favourites_api.dart';
part 'api/growth_api.dart';
part 'api/legal_api.dart';
part 'api/notifications_api.dart';
part 'api/profile_api.dart';
part 'api/safety_api.dart';
part 'api/wallet_api.dart';

part 'model/academy_lesson.dart';
part 'model/academy_lesson_input.dart';
part 'model/academy_lesson_input_quiz_inner.dart';
part 'model/academy_lesson_quiz_inner.dart';
part 'model/add_favourite_request.dart';
part 'model/admin_add_user_note_request.dart';
part 'model/admin_audit_log200_response_inner.dart';
part 'model/admin_call_rate.dart';
part 'model/admin_call_rate_input.dart';
part 'model/admin_coin_package.dart';
part 'model/admin_coin_package_input.dart';
part 'model/admin_create_gift_request.dart';
part 'model/admin_create_package_request.dart';
part 'model/admin_create_rate_request.dart';
part 'model/admin_dashboard200_response.dart';
part 'model/admin_dashboard200_response_activity_inner.dart';
part 'model/admin_dashboard200_response_activity_inner_user.dart';
part 'model/admin_dashboard200_response_by_hour_inner.dart';
part 'model/admin_dashboard200_response_languages_inner.dart';
part 'model/admin_dashboard200_response_live.dart';
part 'model/admin_dashboard200_response_pending_payouts.dart';
part 'model/admin_dashboard200_response_today.dart';
part 'model/admin_dashboard200_response_yesterday.dart';
part 'model/admin_decide_refund_request.dart';
part 'model/admin_gift.dart';
part 'model/admin_gift_input.dart';
part 'model/admin_kyc_case.dart';
part 'model/admin_kyc_case_aadhaar.dart';
part 'model/admin_kyc_case_academy.dart';
part 'model/admin_kyc_case_input.dart';
part 'model/admin_kyc_case_input_aadhaar.dart';
part 'model/admin_kyc_case_input_academy.dart';
part 'model/admin_kyc_decision_request.dart';
part 'model/admin_list_payouts200_response.dart';
part 'model/admin_list_payouts200_response_totals.dart';
part 'model/admin_list_settings200_response_inner.dart';
part 'model/admin_list_users200_response.dart';
part 'model/admin_moderation_flag.dart';
part 'model/admin_moderation_flag_call.dart';
part 'model/admin_moderation_flag_input.dart';
part 'model/admin_moderation_flag_input_call.dart';
part 'model/admin_moderation_flag_input_subject.dart';
part 'model/admin_moderation_flag_subject.dart';
part 'model/admin_note.dart';
part 'model/admin_note_input.dart';
part 'model/admin_payout.dart';
part 'model/admin_payout_companion.dart';
part 'model/admin_payout_input.dart';
part 'model/admin_payout_input_companion.dart';
part 'model/admin_refund.dart';
part 'model/admin_refund_call.dart';
part 'model/admin_refund_caller.dart';
part 'model/admin_refund_companion.dart';
part 'model/admin_refund_input.dart';
part 'model/admin_refund_input_call.dart';
part 'model/admin_refund_input_caller.dart';
part 'model/admin_refund_input_companion.dart';
part 'model/admin_reject_payout_request.dart';
part 'model/admin_report.dart';
part 'model/admin_report_input.dart';
part 'model/admin_report_input_reported.dart';
part 'model/admin_report_input_reporter.dart';
part 'model/admin_report_reported.dart';
part 'model/admin_resolve_moderation_flag_request.dart';
part 'model/admin_resolve_report_request.dart';
part 'model/admin_send_coins200_response.dart';
part 'model/admin_send_coins_request.dart';
part 'model/admin_send_message200_response.dart';
part 'model/admin_send_message_request.dart';
part 'model/admin_set_user_status_request.dart';
part 'model/admin_set_video_request.dart';
part 'model/admin_update_gift_request.dart';
part 'model/admin_update_package_request.dart';
part 'model/admin_update_setting_request.dart';
part 'model/admin_user.dart';
part 'model/admin_user_detail.dart';
part 'model/admin_user_detail_audit_inner.dart';
part 'model/admin_user_detail_calls_inner.dart';
part 'model/admin_user_detail_companion.dart';
part 'model/admin_user_detail_input.dart';
part 'model/admin_user_detail_input_audit_inner.dart';
part 'model/admin_user_detail_input_calls_inner.dart';
part 'model/admin_user_detail_input_companion.dart';
part 'model/admin_user_detail_input_ledger_inner.dart';
part 'model/admin_user_detail_input_payouts_inner.dart';
part 'model/admin_user_detail_input_purchases_inner.dart';
part 'model/admin_user_detail_input_refunds_inner.dart';
part 'model/admin_user_detail_input_reports_inner.dart';
part 'model/admin_user_detail_input_stats.dart';
part 'model/admin_user_detail_ledger_inner.dart';
part 'model/admin_user_detail_payouts_inner.dart';
part 'model/admin_user_detail_purchases_inner.dart';
part 'model/admin_user_detail_refunds_inner.dart';
part 'model/admin_user_detail_reports_inner.dart';
part 'model/admin_user_detail_stats.dart';
part 'model/admin_user_input.dart';
part 'model/answer_lesson_quiz200_response.dart';
part 'model/answer_lesson_quiz_request.dart';
part 'model/apply_as_companion_request.dart';
part 'model/block_user_request.dart';
part 'model/call_details.dart';
part 'model/call_details_gifts_inner.dart';
part 'model/call_details_input.dart';
part 'model/call_details_input_gifts_inner.dart';
part 'model/call_details_input_minutes_inner.dart';
part 'model/call_details_minutes_inner.dart';
part 'model/call_summary.dart';
part 'model/call_summary_input.dart';
part 'model/chat_item.dart';
part 'model/chat_item_input.dart';
part 'model/check_in.dart';
part 'model/check_in_days_inner.dart';
part 'model/check_in_input.dart';
part 'model/check_in_input_days_inner.dart';
part 'model/claim_check_in200_response.dart';
part 'model/companion_earnings200_response.dart';
part 'model/companion_earnings200_response_week_inner.dart';
part 'model/companion_home200_response.dart';
part 'model/companion_home200_response_recent_inner.dart';
part 'model/companion_home200_response_today.dart';
part 'model/companion_rates.dart';
part 'model/companion_rates_input.dart';
part 'model/conversation.dart';
part 'model/conversation_input.dart';
part 'model/conversation_input_other.dart';
part 'model/conversation_other.dart';
part 'model/delete_account200_response.dart';
part 'model/delete_account_request.dart';
part 'model/favourite.dart';
part 'model/favourite_input.dart';
part 'model/flag_video_frame201_response.dart';
part 'model/flag_video_frame202_response.dart';
part 'model/flag_video_frame_request.dart';
part 'model/get_academy200_response.dart';
part 'model/get_chat_messages200_response.dart';
part 'model/get_companion200_response.dart';
part 'model/get_legal_page200_response.dart';
part 'model/get_referral200_response.dart';
part 'model/get_share_card200_response.dart';
part 'model/get_wallet200_response.dart';
part 'model/gift.dart';
part 'model/gift_input.dart';
part 'model/join_info.dart';
part 'model/join_info_input.dart';
part 'model/kyc_state.dart';
part 'model/kyc_state_aadhaar.dart';
part 'model/kyc_state_input.dart';
part 'model/kyc_state_input_aadhaar.dart';
part 'model/kyc_state_input_pan.dart';
part 'model/kyc_state_input_selfie.dart';
part 'model/kyc_state_input_upi.dart';
part 'model/kyc_state_pan.dart';
part 'model/kyc_state_selfie.dart';
part 'model/kyc_state_upi.dart';
part 'model/ledger_entry.dart';
part 'model/ledger_entry_input.dart';
part 'model/legal_block.dart';
part 'model/legal_block_input.dart';
part 'model/legal_cell.dart';
part 'model/legal_cell_input.dart';
part 'model/legal_row.dart';
part 'model/legal_row_input.dart';
part 'model/legal_span.dart';
part 'model/legal_span_input.dart';
part 'model/list_blocks200_response_inner.dart';
part 'model/list_calls200_response.dart';
part 'model/list_chats200_response.dart';
part 'model/list_coin_packages200_response_inner.dart';
part 'model/list_languages200_response_inner.dart';
part 'model/list_ledger200_response.dart';
part 'model/list_legal_pages200_response_inner.dart';
part 'model/list_notifications200_response.dart';
part 'model/list_online_companions200_response.dart';
part 'model/mark_notifications_read_request.dart';
part 'model/match_call201_response.dart';
part 'model/match_call_request.dart';
part 'model/notification_item.dart';
part 'model/notification_item_input.dart';
part 'model/online_companion.dart';
part 'model/online_companion_input.dart';
part 'model/otp_verify_result.dart';
part 'model/otp_verify_result_input.dart';
part 'model/party.dart';
part 'model/party_input.dart';
part 'model/payout.dart';
part 'model/payout_input.dart';
part 'model/profile.dart';
part 'model/profile_companion.dart';
part 'model/profile_input.dart';
part 'model/profile_input_companion.dart';
part 'model/rate_call_request.dart';
part 'model/refresh_tokens_request.dart';
part 'model/refund_request.dart';
part 'model/refund_request_input.dart';
part 'model/register_device_request.dart';
part 'model/report_user201_response.dart';
part 'model/report_user_request.dart';
part 'model/request_payout_request.dart';
part 'model/request_refund_request.dart';
part 'model/send_chat_message_request.dart';
part 'model/send_gift201_response.dart';
part 'model/send_gift_request.dart';
part 'model/send_otp200_response.dart';
part 'model/send_otp_request.dart';
part 'model/set_presence200_response.dart';
part 'model/set_presence_request.dart';
part 'model/set_upi_request.dart';
part 'model/sign_up201_response.dart';
part 'model/sign_up_request.dart';
part 'model/start_call_request.dart';
part 'model/token_pair.dart';
part 'model/token_pair_input.dart';
part 'model/unread_notification_count200_response.dart';
part 'model/update_me_request.dart';
part 'model/upload_aadhaar_request.dart';
part 'model/upload_pan_request.dart';
part 'model/upload_selfie_request.dart';
part 'model/verify_otp_request.dart';


/// An [ApiClient] instance that uses the default values obtained from
/// the OpenAPI specification file.
var defaultApiClient = ApiClient();

const _delimiters = {'csv': ',', 'ssv': ' ', 'tsv': '\t', 'pipes': '|'};
const _dateEpochMarker = 'epoch';
const _deepEquality = DeepCollectionEquality();
final _dateFormatter = DateFormat('yyyy-MM-dd');
final _regList = RegExp(r'^List<(.*)>$');
final _regSet = RegExp(r'^Set<(.*)>$');
final _regMap = RegExp(r'^Map<String,(.*)>$');

bool _isEpochMarker(String? pattern) => pattern == _dateEpochMarker || pattern == '/$_dateEpochMarker/';
