//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.18

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

part of pesu_api;

class AdminSendCoinsRequest {
  /// Returns a new [AdminSendCoinsRequest] instance.
  AdminSendCoinsRequest({
    required this.coins,
    required this.reason,
    required this.requestId,
  });

  /// Minimum value: 1
  /// Maximum value: 10000
  int coins;

  String reason;

  /// Generated by the panel per attempt; a retried click can't credit twice
  String requestId;

  @override
  bool operator ==(Object other) => identical(this, other) || other is AdminSendCoinsRequest &&
    other.coins == coins &&
    other.reason == reason &&
    other.requestId == requestId;

  @override
  int get hashCode =>
    // ignore: unnecessary_parenthesis
    (coins.hashCode) +
    (reason.hashCode) +
    (requestId.hashCode);

  @override
  String toString() => 'AdminSendCoinsRequest[coins=$coins, reason=$reason, requestId=$requestId]';

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
      json[r'coins'] = this.coins;
      json[r'reason'] = this.reason;
      json[r'requestId'] = this.requestId;
    return json;
  }

  /// Returns a new [AdminSendCoinsRequest] instance and imports its values from
  /// [value] if it's a [Map], null otherwise.
  // ignore: prefer_constructors_over_static_methods
  static AdminSendCoinsRequest? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      // Ensure that the map contains the required keys.
      // Note 1: the values aren't checked for validity beyond being non-null.
      // Note 2: this code is stripped in release mode!
      assert(() {
        assert(json.containsKey(r'coins'), 'Required key "AdminSendCoinsRequest[coins]" is missing from JSON.');
        assert(json[r'coins'] != null, 'Required key "AdminSendCoinsRequest[coins]" has a null value in JSON.');
        assert(json.containsKey(r'reason'), 'Required key "AdminSendCoinsRequest[reason]" is missing from JSON.');
        assert(json[r'reason'] != null, 'Required key "AdminSendCoinsRequest[reason]" has a null value in JSON.');
        assert(json.containsKey(r'requestId'), 'Required key "AdminSendCoinsRequest[requestId]" is missing from JSON.');
        assert(json[r'requestId'] != null, 'Required key "AdminSendCoinsRequest[requestId]" has a null value in JSON.');
        return true;
      }());

      return AdminSendCoinsRequest(
        coins: mapValueOfType<int>(json, r'coins')!,
        reason: mapValueOfType<String>(json, r'reason')!,
        requestId: mapValueOfType<String>(json, r'requestId')!,
      );
    }
    return null;
  }

  static List<AdminSendCoinsRequest> listFromJson(dynamic json, {bool growable = false,}) {
    final result = <AdminSendCoinsRequest>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = AdminSendCoinsRequest.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  static Map<String, AdminSendCoinsRequest> mapFromJson(dynamic json) {
    final map = <String, AdminSendCoinsRequest>{};
    if (json is Map && json.isNotEmpty) {
      json = json.cast<String, dynamic>(); // ignore: parameter_assignments
      for (final entry in json.entries) {
        final value = AdminSendCoinsRequest.fromJson(entry.value);
        if (value != null) {
          map[entry.key] = value;
        }
      }
    }
    return map;
  }

  // maps a json object with a list of AdminSendCoinsRequest-objects as value to a dart map
  static Map<String, List<AdminSendCoinsRequest>> mapListFromJson(dynamic json, {bool growable = false,}) {
    final map = <String, List<AdminSendCoinsRequest>>{};
    if (json is Map && json.isNotEmpty) {
      // ignore: parameter_assignments
      json = json.cast<String, dynamic>();
      for (final entry in json.entries) {
        map[entry.key] = AdminSendCoinsRequest.listFromJson(entry.value, growable: growable,);
      }
    }
    return map;
  }

  /// The list of required keys that must be present in a JSON.
  static const requiredKeys = <String>{
    'coins',
    'reason',
    'requestId',
  };
}

